image:
nodeName:
baremetalStorage:
cephRbd:
cephRbdPVCName:
cephRbdStorageClassName:
cephFS:
cephFSPVCName:
cephFSStorageClassName:
nfs:
nfsPVCName:
nfsStorageClassName:

resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 50m
    memory: 128Mi
